#!/usr/bin/env python
# -*- coding: utf-8 -*-
url = [
    'https://nulastudio.org/Freedom/',
    'https://fx.tmioe.com/freessr',
    'https://my.freess.info/',
    'https://get.ishadowx.biz/',
    'https://en.ss8.tech/',
    'https://tz.qwq.cc/ssrlinks.txt',
    'https://fx.tmioe.com/freessr',
    'https://www.attackmen.com/',
    'https://ssrtool.us/tool/share_ssr',
    'https://lncn.org/',
    'https://www.youneed.win/free-ss',
    'https://www.youneed.win/free-ssr',
    'https://www.youneed.win/free-ssr/2',
    'https://www.youneed.win/free-ssr/3',
    'https://fanqiang.network/',
    'https://fanqiang.network/free-shadowsocksr-accounts-page-2',
    'https://fanqiang.network/free-shadowsocksr-accounts-page-3',
    'https://fanqiang.network/free-shadowsocksr-accounts-page-4',
    'https://fanqiang.network/free-shadowsocksr-accounts-page-5',
    'https://t.me/s/SSRSUB',
    'https://t.me/s/SSRlist',
    'https://t.me/s/ssrshares',
    'https://t.me/s/FreeSSRNode',
]

subscriptions = [
    'https://www.liesauer.net/yogurt/subscribe',
    'https://raw.githubusercontent.com/eycorsican/rule-sets/master/kitsunebi_sub',
    'https://haobang.yangwang.workers.dev',
    'https://raw.githubusercontent.com/voken100g/AutoSSR/master/stable',
    'https://raw.githubusercontent.com/voken100g/AutoSSR/master/online',
    'https://raw.githubusercontent.com/voken100g/AutoSSR/master/recent',
    'http://publicsub.getenjoyment.net/alluser.html',
    'https://muma16fx.netlify.com/',
    'https://qiaomenzhuanfx.netlify.com/',
    'https://raw.githubusercontent.com/ssrsub/ssr/master/ssrsub',
    'https://raw.githubusercontent.com/fggfffgbg/https-aishangyou.tube-/master/README.md',
    'http://ss.pythonic.life/subscribe',
]
